export type DomainHealth = "HEALTHY" | "WATCH" | "AT_RISK" | "CRITICAL";
export type IssueStatus = "OPEN" | "TRIAGE" | "PLANNED" | "IN_PROGRESS" | "RESOLVED";
export type IssueSeverity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type PlanStatus = "DRAFT" | "ACTIVE" | "BLOCKED" | "SHIPPED";
export type IncidentStatus = "ACTIVE" | "MONITORING" | "RESOLVED";
export type IncidentSeverity = "SEV1" | "SEV2" | "SEV3";

export const workspace = {
  name: "Foundry Engineering",
  slug: "foundry-engineering",
};

export const domains = [
  {
    id: "identity-platform",
    name: "Identity Platform",
    slug: "identity-platform",
    owner: "Maya Singh",
    health: "WATCH" as DomainHealth,
    system: "Auth, sessions, account security",
    description: "Owns sign-in, workspace membership, session controls, and account recovery.",
    rolloutNotes: "Session changes ship behind edge-scoped flags with support escalation windows.",
    dependencies: ["Email Delivery", "Workspace Directory", "Audit Log"],
  },
  {
    id: "deployment-control-plane",
    name: "Deployment Control Plane",
    slug: "deployment-control-plane",
    owner: "Noah Kim",
    health: "AT_RISK" as DomainHealth,
    system: "Rollouts, flags, deploy orchestration",
    description: "Coordinates release promotion, rollback paths, and operational deploy safety.",
    rolloutNotes: "Critical service rollouts require staged exposure, owner acceptance, and rollback rehearsal recency.",
    dependencies: ["Telemetry Pipeline", "Service Catalog", "Incident Routing"],
  },
  {
    id: "billing-ledger",
    name: "Billing Ledger",
    slug: "billing-ledger",
    owner: "Ari Cohen",
    health: "HEALTHY" as DomainHealth,
    system: "Plans, invoices, usage metering",
    description: "Maintains billing correctness across customer plans, invoices, and usage capture.",
    rolloutNotes: "Ledger migrations run through shadow writes, reconciliation diffs, and finance sign-off.",
    dependencies: ["Usage Metering", "Payment Processor", "Customer Entitlements"],
  },
  {
    id: "telemetry-pipeline",
    name: "Telemetry Pipeline",
    slug: "telemetry-pipeline",
    owner: "Lena Ortiz",
    health: "CRITICAL" as DomainHealth,
    system: "Events, metrics, traces",
    description: "Moves product and infrastructure signals into queryable operational datasets.",
    rolloutNotes: "Collector and schema changes deploy by region with ingestion lag guardrails.",
    dependencies: ["Deployment Control Plane", "Data Warehouse", "Alert Routing"],
  },
  {
    id: "developer-experience",
    name: "Developer Experience",
    slug: "developer-experience",
    owner: "Theo Wallace",
    health: "WATCH" as DomainHealth,
    system: "Local tooling, CI ergonomics, internal docs",
    description: "Keeps the engineering workflow fast, understandable, and reliable at scale.",
    rolloutNotes: "Workflow template changes are piloted with two service teams before broad adoption.",
    dependencies: ["CI Provider", "Service Catalog", "Documentation Platform"],
  },
];

export const issues = [
  {
    id: "canary-ownership-gates",
    domainSlug: "deployment-control-plane",
    title: "Canary promotion lacks service-level ownership gates",
    summary: "Rollouts can advance without confirming each owning domain has accepted the blast radius.",
    status: "IN_PROGRESS" as IssueStatus,
    severity: "HIGH" as IssueSeverity,
    risk: "A deploy can widen before a domain owner has validated the operational signal.",
    rollout: "Introduce owner sign-off for services with elevated error budgets.",
    plan: {
      title: "Owner-aware canary promotion",
      status: "ACTIVE" as PlanStatus,
      approach: "Add domain ownership metadata to rollout policies, require explicit acceptance for high-risk services, and record override rationale.",
      edgeCases: "Emergency overrides, missing ownership metadata, and services spanning multiple domains must degrade to an explicit human approval path.",
      testPlan: "Cover policy evaluation, override audit records, stale owner data, and mixed-risk rollout batches with integration tests.",
      rolloutPlan: "Enable in report-only mode for critical services, compare recommendations for one week, then enforce on sev-prone domains first.",
      monitoringPlan: "Track blocked promotions, override rate, rollout duration, and owner acknowledgement latency by domain.",
      rollbackPlan: "Disable enforcement through the rollout policy flag and preserve audit writes for later review.",
      owner: "Noah Kim",
      targetDate: "2026-07-18T00:00:00.000Z",
    },
  },
  {
    id: "trace-backpressure-visibility",
    domainSlug: "telemetry-pipeline",
    title: "Trace ingestion backpressure is invisible to service owners",
    summary: "Owners discover dropped traces through customer reports instead of operational signals.",
    status: "TRIAGE" as IssueStatus,
    severity: "CRITICAL" as IssueSeverity,
    risk: "Incident diagnosis slows down when trace gaps are found after the fact.",
    rollout: "Ship per-domain ingestion health and alert routing.",
    plan: {
      title: "Domain-scoped telemetry health",
      status: "DRAFT" as PlanStatus,
      approach: "Expose ingestion lag, drop rate, and sampling pressure by domain, then route alerts to the responsible owner channel.",
      edgeCases: "Unmapped services, bursty trace producers, and region-local collector failures need explicit fallback labels.",
      testPlan: "Replay high-volume trace batches, force collector throttling, and verify alert fan-out to the right owner.",
      rolloutPlan: "Launch dashboards first, then paging alerts for critical domains after owners confirm thresholds.",
      monitoringPlan: "Watch lag p95, dropped spans, queue saturation, and alert acknowledgement time.",
      rollbackPlan: "Turn off owner paging while keeping dashboards available if signal quality is noisy.",
      owner: "Lena Ortiz",
      targetDate: "2026-07-26T00:00:00.000Z",
    },
  },
  {
    id: "session-revocation-consistency",
    domainSlug: "identity-platform",
    title: "Session revocation does not propagate consistently",
    summary: "Password reset and admin lockout flows can leave some edge sessions alive.",
    status: "OPEN" as IssueStatus,
    severity: "HIGH" as IssueSeverity,
    risk: "Compromised credentials may retain access longer than expected.",
    rollout: "Move revocation checks to a single authoritative session ledger.",
  },
  {
    id: "usage-replay-reconciliation",
    domainSlug: "billing-ledger",
    title: "Usage replay tooling needs deterministic reconciliation",
    summary: "Metering repairs are still too manual during customer support escalations.",
    status: "PLANNED" as IssueStatus,
    severity: "MEDIUM" as IssueSeverity,
    risk: "Revenue-impacting corrections depend on specialist knowledge.",
    rollout: "Add audited replay jobs for scoped customer windows.",
    plan: {
      title: "Audited usage replay",
      status: "ACTIVE" as PlanStatus,
      approach: "Build a constrained replay command with dry-run diffs, immutable repair records, and billing-owner approval.",
      edgeCases: "Partial invoices, deleted entitlements, and replay windows crossing plan changes require deterministic handling.",
      testPlan: "Run replay fixtures for plan transitions, late events, duplicate events, and customer-scoped corrections.",
      rolloutPlan: "Start with internal accounts, then support-led repairs under billing owner supervision.",
      monitoringPlan: "Track replay duration, reconciliation delta, approval latency, and repeated customer repairs.",
      rollbackPlan: "Cancel pending replay jobs and revert to manual correction using the last dry-run snapshot.",
      owner: "Ari Cohen",
      targetDate: "2026-08-04T00:00:00.000Z",
    },
  },
  {
    id: "ci-ownership-signal",
    domainSlug: "developer-experience",
    title: "CI ownership signal is lost in shared workflows",
    summary: "Broken shared jobs are hard to route because ownership metadata stops at the repository boundary.",
    status: "OPEN" as IssueStatus,
    severity: "MEDIUM" as IssueSeverity,
    risk: "Failures linger and release confidence drops across unrelated teams.",
    rollout: "Attach domain ownership to workflow templates and failure notifications.",
  },
  {
    id: "rollback-rehearsal-tracking",
    domainSlug: "deployment-control-plane",
    title: "Rollback rehearsals are not tracked against critical services",
    summary: "The team has no current view of which systems have recently exercised rollback paths.",
    status: "OPEN" as IssueStatus,
    severity: "HIGH" as IssueSeverity,
    risk: "Rollback procedures may fail under incident pressure.",
    rollout: "Record rollback rehearsal recency for each owned service.",
  },
  {
    id: "metrics-cardinality-budget",
    domainSlug: "telemetry-pipeline",
    title: "Metrics cardinality budget has no domain owner workflow",
    summary: "Cardinality spikes are handled centrally instead of being fed back to system owners.",
    status: "IN_PROGRESS" as IssueStatus,
    severity: "MEDIUM" as IssueSeverity,
    risk: "Telemetry cost and query latency grow without domain-level accountability.",
    rollout: "Create budgets, alerts, and owner acknowledgements per domain.",
    plan: {
      title: "Domain-owned cardinality budgets",
      status: "DRAFT" as PlanStatus,
      approach: "Introduce per-domain metric budgets and route threshold exceptions to the owning system team.",
      edgeCases: "",
      testPlan: "Replay high-cardinality metric fixtures and verify budget classification by domain.",
      rolloutPlan: "Start in report-only mode for telemetry-heavy domains before enforcing budget notifications.",
      monitoringPlan: "",
      rollbackPlan: "",
      owner: "Lena Ortiz",
      targetDate: "2026-08-12T00:00:00.000Z",
    },
  },
  {
    id: "account-recovery-runbook",
    domainSlug: "identity-platform",
    title: "Account recovery runbook is stale after support tooling changes",
    summary: "Operational guidance no longer matches the current escalation path.",
    status: "RESOLVED" as IssueStatus,
    severity: "LOW" as IssueSeverity,
    risk: "Support escalations may take longer during rare recovery failures.",
    rollout: "Update runbook and add quarterly verification ownership.",
  },
];

export const incidents = [
  {
    id: "trace-ingest-lag-eu",
    domainSlug: "telemetry-pipeline",
    title: "Trace ingest lag across EU region",
    summary: "Trace ingestion delayed by queue saturation after a collector rollout.",
    impact: "EU service owners lost fresh trace visibility for 42 minutes during active incident diagnosis.",
    rootCause: "Collector rollout increased retry volume without matching queue capacity for high-cardinality services.",
    resolution: "Paused the rollout, drained queues, and reduced sampling pressure for the affected region.",
    prevention: "Add region-level ingestion budgets and owner-facing backpressure alerts before collector promotion.",
    postmortemRequired: true,
    status: "ACTIVE" as IncidentStatus,
    severity: "SEV2" as IncidentSeverity,
    startedAt: "2026-06-28T18:20:00.000Z",
  },
  {
    id: "flag-propagation-delay",
    domainSlug: "deployment-control-plane",
    title: "Flag propagation delay during staged rollout",
    summary: "A staged rollout paused after flag state took longer than expected to converge.",
    impact: "One customer-facing rollout paused for 26 minutes while owners verified exposure state.",
    rootCause: "Propagation workers were healthy globally but lagged in one shard with no owner-visible signal.",
    resolution: "Rebalanced the shard and held promotion until convergence matched policy.",
    prevention: "Expose per-shard propagation lag and block promotion when convergence is outside policy.",
    postmortemRequired: true,
    status: "MONITORING" as IncidentStatus,
    severity: "SEV3" as IncidentSeverity,
    startedAt: "2026-06-27T10:45:00.000Z",
  },
  {
    id: "magic-link-delivery-failures",
    domainSlug: "identity-platform",
    title: "Elevated magic-link delivery failures",
    summary: "A vendor routing issue caused delayed account access emails for a subset of users.",
    impact: "A subset of users waited up to 18 minutes for account access links.",
    rootCause: "Email provider routing degraded in one delivery path and fallback was not triggered quickly enough.",
    resolution: "Forced traffic to the secondary route and verified delivery latency returned to baseline.",
    prevention: "Tighten provider failover thresholds and add recovery-path verification to the ownership checklist.",
    postmortemRequired: false,
    status: "RESOLVED" as IncidentStatus,
    severity: "SEV3" as IncidentSeverity,
    startedAt: "2026-06-23T09:15:00.000Z",
    resolvedAt: "2026-06-23T11:05:00.000Z",
  },
];
